name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say Hello
        run: echo "Hello pipelines' world !"
      
      - name: Display runner info
        run: |
          echo "Running on: $(uname -a)"
          echo "Workflow: ${{ github.workflow }}"
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
