name: Run Lab2 Script
on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4 

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm' 

      - name: Installer les dépendances
        run: |
          pnpm config set shamefully-hoist true
          pnpm install --shamefully-hoist

      - name: Lancer le script lab2
        run: |
          chmod +x ./pipelines/script.sh
          ./pipelines/script.sh