name: Pipeline CI/CD Parallélisée - Lab2

on:
  push:
    branches:
      - main
      - lab2
      - lab3
      - 'feature/*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Installation des dépendances
        run: pnpm install --frozen-lockfile

      - name: Vérification Qualité (Lint et Typecheck)
        run: |
          pnpm lint
          pnpm typecheck

      - name: Exécution des Tests 
        run: pnpm test

  
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Installation des dépendances
        run: pnpm install --frozen-lockfile

      - name: Construction du package (Build)
        run: pnpm build

      - name: Vérification du fonctionnement du package
        run: |
          if [ -d ".output" ] && [ -f ".output/server/index.mjs" ]; then
            echo "Succès : Le dossier .output est valide"
          else
            echo "Erreur : Le build a échoué (fichiers manquants)"
            exit 1
          fi

      - name: Upload des artefacts de build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .output/server/index.mjs
          retention-days: 7